[[redirects]]
  from = "https://uberflip-proxy.netlify.app/hub"
  to = "https://read.uberflip.com/hub"
  status = 200
  force = true
  headers = {X-Original-Host = "uberflip-proxy.netlify.app", X-Forwarded-Host = "uberflip-proxy.netlify.app", X-Netlify-Hostname = "uberflip-proxy.netlify.app" }
[[redirects]]
  from = "https://uberflip-proxy.netlify.app/hub/*"
  to = "https://read.uberflip.com/hub/:splat"
  status = 200
  force = true
  headers = {X-Original-Host = "uberflip-proxy.netlify.app", X-Forwarded-Host = "uberflip-proxy.netlify.app", X-Netlify-Hostname = "uberflip-proxy.netlify.app" }
